spring.application.name=java-socket-daemon
spring.main.web-application-type=none

mybatis.mapper-locations=classpath:mapper/*.xml

spring.profiles.active=local

daemon.nas-ip=127.0.0.1
daemon.poll-interval-ms=2000

daemon.socket.connect-timeout-ms=3000
daemon.socket.read-timeout-ms=30000
daemon.socket.retry-count=3
daemon.socket.jitter-ms=200
daemon.socket.retry-backoff-ms=500

daemon.conf.dir=config/provider
