spring.application.name=java-socket-daemon
spring.main.web-application-type=none

mybatis.mapper-locations=classpath:mapper/*.xml

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000

daemon.nas-ip=${DAEMON_NAS_IP}
daemon.poll-interval-ms=2000

daemon.socket.connect-timeout-ms=3000
daemon.socket.read-timeout-ms=30000
daemon.socket.retry-count=3
daemon.socket.jitter-ms=200
daemon.socket.retry-backoff-ms=500

daemon.conf.dir=/app/config/provider

daemon.socket.mock-enabled=false
